server:
  port: 10040

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${db-url}:${db-port}/${db-kungca}
    username: ${db-user}
    password: ${db-pw}
  config:
    activate:
      on-profile: ${profile}


  jpa:
    hibernate:
      ddl-auto: update